# Generated by Django 3.1.7 on 2021-03-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AminoAcid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot', models.CharField(max_length=6, unique=True)),
                ('kingdom', models.CharField(choices=[('0', 'EUKARYA'), ('-1', 'NEGATIVE'), ('1', 'POSITIVE')], max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('partition_number', models.IntegerField()),
                ('sequence_1', models.CharField(max_length=70)),
                ('sequence_2', models.CharField(max_length=70)),
            ],
        ),
    ]
