# Generated by Django 3.1.7 on 2021-03-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aminoacid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aminoacid',
            name='kingdom',
            field=models.CharField(choices=[('EUK', 'EUKARYA'), ('NEG', 'NEGATIVE'), ('POS', 'POSITIVE'), ('ARC', 'ARCHAEA')], max_length=10),
        ),
    ]
