# Generated by Django 3.1.7 on 2021-03-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aminoacid', '0002_auto_20210312_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aminoacid',
            name='sequence_1',
        ),
        migrations.RemoveField(
            model_name='aminoacid',
            name='sequence_2',
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='sequence',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
    ]
